Repository eug-vs/chrono-cube, pull requests merged in 2020-01, with the labels that each got.

#11 Create functions for GET and POST requests
  package-lock.json
  package.json
  src/requests.js
Labels: high priority

#13 Implement Scoreboard functionality
  src/components/Scoreboard/Scoreboard.js
  src/components/Scoreboard/Solution.js
  src/index.js
Labels: feature

#12 Implement core timer functionality
  src/components/Timer/Timer.js
  src/index.js
Labels: feature

#15 Implement full countdown functionality
  src/components/Timer/Timer.js
Labels: help wanted

#14 Create theme and style existing components
  package-lock.json
  package.json
  src/components/Header/Header.js
  src/components/Scoreboard/Scoreboard.js
  src/components/Scoreboard/Solution.js
  src/components/Timer/Timer.js
  src/index.js
  src/theme.js
Labels: feature

#17 Fix Tabs warning
  src/components/Header/Header.js
  src/index.js
Labels: bug

#25 Fix console warnings
  src/components/Header/Header.js
  src/components/Scoreboard/Scoreboard.js
Labels: bug

#29 Markup Timer page
  src/components/Timer/Timer.js
  src/components/TimerPage/TimerPage.js
  src/index.js
Labels: feature

#30 Implement virtualized rendering
  package-lock.json
  package.json
  src/components/Scoreboard/Scoreboard.js
  src/components/SmartList/SmartList.js
  src/index.js
Labels: feature

#32 Create Window component and refactor existing pages to use it
  package-lock.json
  package.json
  src/components/ContentSection/ContentSection.js
  src/components/Scoreboard/Scoreboard.js
  src/components/SmartList/SmartList.js
  src/components/TimerPage/Timer/Timer.js
  src/components/TimerPage/TimerPage.js
  src/components/Window/Window.js
  src/components/Window/WindowSurface/WindowSurface.js
  src/theme.js
Labels: feature, high priority

#31 Improve requests logic on Scoreboard page
  src/components/Scoreboard/Scoreboard.js
  src/components/SolutionCard/SolutionCard.js
Labels: enhancement

#33 Contribute section support
  package-lock.json
  package.json
  src/components/ContentSection/ContentSection.js
  src/components/SmartList/SmartList.js
  src/components/Window/WindowSurface/WindowSurface.js
  src/developers.json
  src/index.js
  src/pages/Contribute/Contribute.js
  src/pages/Scoreboard/Scoreboard.js
  src/pages/Timer/Timer.js
  src/pages/Timer/TimerButton/TimerButton.js
Labels: documentation, feature

#35 Markup Profile page
  src/index.js
  src/pages/Profile/Profile.js
  src/pages/Profile/Registration/Registration.js
  src/pages/Timer/Timer.js
  src/pages/Timer/TimerButton/TimerButton.js
Labels: feature

#43 docs: add soleni to developers
  src/developers.json
Labels: documentation, invalid

#40 feat: configure ESlint
  .eslintrc.json
  package-lock.json
  package.json
  src/components/ContentSection/ContentSection.js
  src/components/Header/Header.js
  src/components/Loading/Loading.js
  src/components/SolutionCard/SolutionCard.js
  src/components/Window/Window.js
  src/components/Window/WindowSurface/WindowSurface.js
  src/index.js
  src/pages/Contribute/Contribute.js
  src/pages/Profile/Profile.js
  src/pages/Profile/Registration/Registration.js
  src/pages/Scoreboard/Scoreboard.js
  src/pages/Timer/Timer.js
  src/pages/Timer/TimerButton/TimerButton.js
Labels: enhancement

#44 Configure circleCI
  .circleci/config.yml
Labels: feature

#47 Migrate to BENZIN
  package-lock.json
  package.json
  public/favicon.png
  public/index.html
  src/components/ContentSection/ContentSection.js
  src/components/Header/Header.js
  src/components/Loading/Loading.js
  src/components/SmartList/SmartList.js
  src/components/SolutionCard/SolutionCard.js
  src/components/Window/Window.js
  src/components/Window/WindowSurface/WindowSurface.js
  src/index.js
  src/pages/Contribute/Contribute.js
  src/pages/Profile/Profile.js
  src/pages/Profile/Registration/Registration.js
  src/pages/Scoreboard/Scoreboard.js
  src/pages/Timer/Timer.js
  src/pages/Timer/TimerButton/TimerButton.js
  src/theme.js
Labels: feature
